const cron = require('node-cron');
const Task = require('../models/Task');
const Client = require('../models/Client');

/**
 * Monthly Cron Job: Runs at midnight on 1st of every month to generate recurring tasks
 */
const startRecurringTaskCron = () => {
  cron.schedule('0 0 1 * *', async () => {
    console.log('[Cron Engine] Running automatic monthly recurring task generator...');
    try {
      // Find active recurring tasks
      const activeRecurringTasks = await Task.find({
        repeat: { $in: ['Monthly', 'Quarterly', 'Yearly'] },
        status: { $in: ['Completed', 'Pending', 'In Progress'] }
      }).populate('client');

      let generatedCount = 0;
      for (const task of activeRecurringTasks) {
        // Skip if client is deactivated or inactive
        if (!task.client || task.client.status !== 'Active') {
          continue;
        }

        // Calculate next due date
        const currentDueDate = new Date(task.dueDate);
        let nextDueDate = new Date(currentDueDate);

        if (task.repeat === 'Monthly') {
          nextDueDate.setMonth(nextDueDate.getMonth() + 1);
        } else if (task.repeat === 'Quarterly') {
          nextDueDate.setMonth(nextDueDate.getMonth() + 3);
        } else if (task.repeat === 'Yearly') {
          nextDueDate.setFullYear(nextDueDate.getFullYear() + 1);
        }

        // Check if task for next due date already exists
        const existingTask = await Task.findOne({
          client: task.client._id,
          taskName: task.taskName,
          dueDate: {
            $gte: new Date(nextDueDate.getFullYear(), nextDueDate.getMonth(), 1),
            $lte: new Date(nextDueDate.getFullYear(), nextDueDate.getMonth() + 1, 0)
          }
        });

        if (!existingTask) {
          await Task.create({
            client: task.client._id,
            department: task.department,
            taskName: task.taskName,
            priority: task.priority,
            assignedEmployee: task.assignedEmployee,
            dueDate: nextDueDate,
            reminderDays: task.reminderDays,
            repeat: task.repeat,
            status: 'Pending',
            remarks: `Auto-generated ${task.repeat} task for ${task.taskName}`,
            isAutoGenerated: true,
            parentTaskId: task._id
          });
          generatedCount++;
        }
      }
      console.log(`[Cron Engine] Auto-generated ${generatedCount} recurring tasks for active clients.`);
    } catch (err) {
      console.error('[Cron Engine Error]', err.message);
    }
  });
};

module.exports = { startRecurringTaskCron };
