const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema(
  {
    client: { type: mongoose.Schema.Types.ObjectId, ref: 'Client', required: true },
    department: {
      type: String,
      enum: ['GST', 'Book Keeping', 'IT Filing', 'Registration'],
      required: true
    },
    taskName: { type: String, required: true }, // e.g. GSTR3B, GSTR1, Tax Audit, Bank Reconciliation, etc.
    priority: {
      type: String,
      enum: ['Low', 'Medium', 'High', 'Critical'],
      default: 'Medium'
    },
    assignedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    assignedEmployee: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    assignedDate: { type: Date, default: Date.now },
    dueDate: { type: Date, required: true },
    reminderDays: { type: Number, default: 3 },
    repeat: {
      type: String,
      enum: ['Monthly', 'Quarterly', 'Yearly', 'One Time'],
      default: 'One Time'
    },
    status: {
      type: String,
      enum: ['Pending', 'In Progress', 'Waiting', 'Completed', 'On Hold', 'Cancelled'],
      default: 'Pending'
    },
    remarks: { type: String },
    attachment: { type: String },
    isAutoGenerated: { type: Boolean, default: false },
    parentTaskId: { type: mongoose.Schema.Types.ObjectId, ref: 'Task' }
  },
  { timestamps: true }
);

module.exports = mongoose.model('Task', taskSchema);
