// Professional Export Utilities for Royal Accounting ERP

export const exportToCSV = (filename, rows, headers) => {
  if (!rows || !rows.length) {
    alert('No data available to export');
    return;
  }

  const separator = ',';
  const headerKeys = Object.keys(headers);
  const headerLabels = Object.values(headers);

  const csvContent = [
    headerLabels.join(separator),
    ...rows.map((row) =>
      headerKeys
        .map((key) => {
          let cell = key.split('.').reduce((obj, i) => (obj ? obj[i] : ''), row);
          if (cell === null || cell === undefined) cell = '';
          cell = String(cell).replace(/"/g, '""');
          if (cell.search(/("|,|\n)/g) >= 0) {
            cell = `"${cell}"`;
          }
          return cell;
        })
        .join(separator)
    )
  ].join('\n');

  const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}_${new Date().toISOString().split('T')[0]}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const printExecutiveReport = ({
  filters = {},
  counters = {},
  tasks = [],
  invoices = [],
  user = {}
}) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to print/export the executive report');
    return;
  }

  const dateGenerated = new Date().toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Royal Accounting - Executive Operations Report</title>
        <style>
          @page { size: A4 portrait; margin: 15mm; }
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #1e293b; margin: 0; padding: 10px; font-size: 11px; }
          .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #C59B27; padding-bottom: 12px; margin-bottom: 14px; }
          .firm-title { font-size: 18px; font-weight: 800; color: #0A1E3F; margin: 0; }
          .firm-sub { font-size: 10px; color: #C59B27; font-weight: 700; text-transform: uppercase; margin-top: 2px; }
          .meta { text-align: right; font-size: 10px; color: #64748b; }
          .filter-bar { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 8px 12px; margin-bottom: 14px; display: flex; gap: 16px; font-size: 10px; }
          .filter-item { font-weight: 600; }
          .filter-item strong { color: #0A1E3F; }
          .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 16px; }
          .card { background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 10px; text-align: center; }
          .card-num { font-size: 16px; font-weight: 800; color: #0A1E3F; margin-top: 3px; }
          .card-lbl { font-size: 9px; font-weight: 700; text-transform: uppercase; color: #64748b; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 10px; }
          th { background: #0A1E3F; color: #ffffff; font-weight: 700; text-align: left; padding: 7px 8px; }
          td { border-bottom: 1px solid #e2e8f0; padding: 6px 8px; }
          tr:nth-child(even) { background-color: #f8fafc; }
          .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 9px; font-weight: 700; }
          .badge-completed { background: #fef3c7; color: #92400e; border: 1px solid #fde68a; }
          .badge-progress { background: #e0f2fe; color: #0369a1; }
          .badge-assigned { background: #f1f5f9; color: #475569; }
          .badge-overdue { background: #ffe4e6; color: #9f1239; }
          .footer { margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 10px; display: flex; justify-content: space-between; font-size: 9px; color: #94a3b8; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 class="firm-title">ROYAL ACCOUNTING</h1>
            <div class="firm-sub">Auditor ERP • Executive Performance & Operations Report</div>
            <div style="font-size: 9.5px; color: #64748b; margin-top: 3px;">GST • Income Tax • Accounting • Certifications • Ph: +91 99943 60994</div>
          </div>
          <div class="meta">
            <div><strong>Generated By:</strong> ${user?.name || 'Logunathan'} (${user?.role || 'Super Admin'})</div>
            <div><strong>Generated At:</strong> ${dateGenerated}</div>
          </div>
        </div>

        <div class="filter-bar">
          <div class="filter-item">Period: <strong>${filters.dateFilter || 'Today'}</strong></div>
          <div class="filter-item">Department: <strong>${filters.department || 'All Departments'}</strong></div>
          <div class="filter-item">Executive: <strong>${filters.employeeName || 'All Executives'}</strong></div>
        </div>

        <div class="grid">
          <div class="card">
            <div class="card-lbl">Total Clients</div>
            <div class="card-num">${counters.totalClients || 0}</div>
          </div>
          <div class="card">
            <div class="card-lbl">Active In Progress</div>
            <div class="card-num">${counters.inProgressTasksCount || 0}</div>
          </div>
          <div class="card">
            <div class="card-lbl">Completed Tasks</div>
            <div class="card-num">${counters.completedTasksCount || 0}</div>
          </div>
          <div class="card">
            <div class="card-lbl">Total Billing Value</div>
            <div class="card-num">₹${(counters.totalBillingValue || 0).toLocaleString('en-IN')}</div>
          </div>
        </div>

        <h3 style="font-size: 12px; font-weight: 800; color: #0A1E3F; margin: 14px 0 6px 0;">Detailed Client Task & Operations Breakdown (${tasks.length} Records)</h3>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Client Name</th>
              <th>Service / Return</th>
              <th>Department</th>
              <th>Executive</th>
              <th>Due Date</th>
              <th>Priority</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            ${
              tasks.length === 0
                ? '<tr><td colspan="8" style="text-align: center; padding: 15px; color: #94a3b8;">No records found for current filter</td></tr>'
                : tasks
                    .map((t, idx) => {
                      const statusClass =
                        t.status === 'Completed'
                          ? 'badge-completed'
                          : t.status === 'In Progress'
                          ? 'badge-progress'
                          : 'badge-assigned';
                      return `
                      <tr>
                        <td>${idx + 1}</td>
                        <td><strong>${t.client?.clientName || 'General Task'}</strong></td>
                        <td>${t.taskName}</td>
                        <td>${t.department}</td>
                        <td>${t.assignedEmployee?.name || 'Unassigned'}</td>
                        <td>${new Date(t.dueDate).toLocaleDateString('en-IN')}</td>
                        <td>${t.priority}</td>
                        <td><span class="badge ${statusClass}">${t.status}</span></td>
                      </tr>
                    `;
                    })
                    .join('')
            }
          </tbody>
        </table>

        <div class="footer">
          <div>Confidential • Royal Accounting ERP Operations • royallogu2020@gmail.com</div>
          <div>Page 1 of 1</div>
        </div>

        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
};
